# Generated by Django 5.1.7 on 2025-04-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_order_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
