# Generated by Django 5.1.7 on 2025-04-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
