# Generated by Django 5.1.7 on 2025-05-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options'),
    ]

    operations = [
    ]
